package catalogo.vistas;

import catalogo.Catalogo;
import catalogo.controladores.JPA.VendedorJpaController;
import catalogo.modelo.Vendedor;
import catalogo.vistas.modelo.VendedorTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Mauro Federico Lopez
 */
public class AdministrarVendedoresUI extends javax.swing.JPanel {

    private VendedorJpaController vendedorJpaController;
    private VendedorTableModel vendedorTableModel;

    /**
     * Creates new form AdministrarVendedoresUI
     */
    public AdministrarVendedoresUI() {
        initComponents();
        vendedorJpaController = Catalogo.getVendedorJpaController();
        vendedorTableModel = new VendedorTableModel();
        tablaVendedores.setModel(vendedorTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuevoVendedorUI = new javax.swing.JDialog();
        etiquetaApellido = new javax.swing.JLabel();
        campoApellido = new javax.swing.JTextField();
        etiquetaNombre = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        etiquetaCorreo = new javax.swing.JLabel();
        campoCorreo = new javax.swing.JTextField();
        etiquetaTelefono = new javax.swing.JLabel();
        campoTelefono = new javax.swing.JFormattedTextField();
        etiquetaUsername = new javax.swing.JLabel();
        campoUsername = new javax.swing.JTextField();
        etiquetaPassword = new javax.swing.JLabel();
        campoPassword = new javax.swing.JPasswordField();
        botonGuardarCliente = new javax.swing.JButton();
        jsp = new javax.swing.JScrollPane();
        tablaVendedores = new javax.swing.JTable();
        panelBotones = new javax.swing.JPanel();
        botonNuevoVendedor = new javax.swing.JButton();
        botonEliminarVendedor = new javax.swing.JButton();

        nuevoVendedorUI.setTitle("Nuevo cliente");
        nuevoVendedorUI.setMinimumSize(new java.awt.Dimension(257, 201));

        etiquetaApellido.setText("Apellido");

        etiquetaNombre.setText("Nombre");

        etiquetaCorreo.setText("Correo");

        etiquetaTelefono.setText("Teléfono");

        campoTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##########"))));

        etiquetaUsername.setText("Nombre de usuario");

        etiquetaPassword.setText("Contraseña");

        botonGuardarCliente.setText("Guardar");
        botonGuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nuevoVendedorUILayout = new javax.swing.GroupLayout(nuevoVendedorUI.getContentPane());
        nuevoVendedorUI.getContentPane().setLayout(nuevoVendedorUILayout);
        nuevoVendedorUILayout.setHorizontalGroup(
            nuevoVendedorUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoVendedorUILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nuevoVendedorUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etiquetaUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaTelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaCorreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etiquetaApellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevoVendedorUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonGuardarCliente)
                    .addGroup(nuevoVendedorUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(campoApellido)
                        .addComponent(campoNombre)
                        .addComponent(campoCorreo)
                        .addComponent(campoUsername)
                        .addComponent(campoTelefono)
                        .addComponent(campoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nuevoVendedorUILayout.setVerticalGroup(
            nuevoVendedorUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoVendedorUILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nuevoVendedorUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevoVendedorUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNombre)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevoVendedorUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaCorreo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevoVendedorUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaTelefono))
                .addGap(6, 6, 6)
                .addGroup(nuevoVendedorUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nuevoVendedorUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonGuardarCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vendedores", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20))); // NOI18N
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setLayout(new java.awt.BorderLayout());

        tablaVendedores.setModel(new catalogo.vistas.modelo.VendedorTableModel());
        tablaVendedores.getTableHeader().setReorderingAllowed(false);
        jsp.setViewportView(tablaVendedores);

        add(jsp, java.awt.BorderLayout.CENTER);

        panelBotones.setMaximumSize(new java.awt.Dimension(32767, 23));
        panelBotones.setMinimumSize(new java.awt.Dimension(100, 23));

        botonNuevoVendedor.setText("Nuevo Vendedor");
        botonNuevoVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoVendedorActionPerformed(evt);
            }
        });
        panelBotones.add(botonNuevoVendedor);

        botonEliminarVendedor.setText("Eliminar Vendedor");
        botonEliminarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarVendedorActionPerformed(evt);
            }
        });
        panelBotones.add(botonEliminarVendedor);

        add(panelBotones, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void botonNuevoVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoVendedorActionPerformed
        campoApellido.setText("");
        campoNombre.setText("");
        campoCorreo.setText("");
        campoTelefono.setValue(null);
        campoUsername.setText("");
        campoPassword.setText("");
        nuevoVendedorUI.setVisible(true);
        nuevoVendedorUI.pack();
    }//GEN-LAST:event_botonNuevoVendedorActionPerformed

    private void botonGuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarClienteActionPerformed
        try {
            String apellido = campoApellido.getText();
            String nombre = campoNombre.getText();
            String correo = campoCorreo.getText();
            Long telefono = ((Number) campoTelefono.getValue()).longValue();
            String username = campoUsername.getText();
            String password = campoPassword.getText();
            vendedorJpaController.registrarNuevoVendedor(apellido, nombre, correo, telefono, username, password);
            nuevoVendedorUI.setVisible(false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonGuardarClienteActionPerformed

    private void botonEliminarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarVendedorActionPerformed
        try {
            Integer filaSeleccionada = tablaVendedores.getSelectedRow();
            if (filaSeleccionada >= 0) {
                Vendedor vendedor = vendedorTableModel.obtenerCliente(filaSeleccionada);
                vendedorJpaController.destruirVendedor(vendedor.getId());
            } else {
                throw new Exception("No ha seleccionado ningún vendedor.");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            tablaVendedores.clearSelection();
        }
    }//GEN-LAST:event_botonEliminarVendedorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEliminarVendedor;
    private javax.swing.JButton botonGuardarCliente;
    private javax.swing.JButton botonNuevoVendedor;
    private javax.swing.JTextField campoApellido;
    private javax.swing.JTextField campoCorreo;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JPasswordField campoPassword;
    private javax.swing.JFormattedTextField campoTelefono;
    private javax.swing.JTextField campoUsername;
    private javax.swing.JLabel etiquetaApellido;
    private javax.swing.JLabel etiquetaCorreo;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaPassword;
    private javax.swing.JLabel etiquetaTelefono;
    private javax.swing.JLabel etiquetaUsername;
    private javax.swing.JScrollPane jsp;
    private javax.swing.JDialog nuevoVendedorUI;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JTable tablaVendedores;
    // End of variables declaration//GEN-END:variables
}
