/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package catalogo.vistas;

/**
 *
 * @author Mauro
 */
public class AdministrarProductosUI extends javax.swing.JPanel {

    /**
     * Creates new form AdministrarProductosUI
     */
    public AdministrarProductosUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaTitulo = new javax.swing.JLabel();
        jsp = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        panelBotones = new javax.swing.JPanel();
        botonNuevoProducto = new javax.swing.JButton();
        botonEliminarProducto = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        etiquetaTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        etiquetaTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTitulo.setText("Productos");
        add(etiquetaTitulo, java.awt.BorderLayout.PAGE_START);

        tablaProductos.setModel(new catalogo.vistas.modelo.ProductoTableModel());
        tablaProductos.getTableHeader().setReorderingAllowed(false);
        jsp.setViewportView(tablaProductos);

        add(jsp, java.awt.BorderLayout.CENTER);

        panelBotones.setMaximumSize(new java.awt.Dimension(32767, 23));
        panelBotones.setMinimumSize(new java.awt.Dimension(100, 23));

        botonNuevoProducto.setText("Nuevo Producto");

        botonEliminarProducto.setText("Eliminar Producto");

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addComponent(botonNuevoProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonEliminarProducto)
                .addGap(0, 454, Short.MAX_VALUE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(botonNuevoProducto)
                .addComponent(botonEliminarProducto))
        );

        add(panelBotones, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEliminarProducto;
    private javax.swing.JButton botonNuevoProducto;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JScrollPane jsp;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables
}
