/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package catalogo.vistas;

/**
 *
 * @author Mauro
 */
public class AdministrarClientesUI extends javax.swing.JPanel {

    /**
     * Creates new form AdministrarClientesUI
     */
    public AdministrarClientesUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaTitulo = new javax.swing.JLabel();
        jsp = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        panelBotones = new javax.swing.JPanel();
        botonNuevoCliente = new javax.swing.JButton();
        botonEliminarCliente = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        etiquetaTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        etiquetaTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTitulo.setText("Clientes");
        add(etiquetaTitulo, java.awt.BorderLayout.PAGE_START);

        tablaClientes.setModel(new catalogo.vistas.modelo.ClienteTableModel());
        tablaClientes.getTableHeader().setReorderingAllowed(false);
        jsp.setViewportView(tablaClientes);

        add(jsp, java.awt.BorderLayout.CENTER);

        panelBotones.setMaximumSize(new java.awt.Dimension(32767, 23));
        panelBotones.setMinimumSize(new java.awt.Dimension(100, 23));

        botonNuevoCliente.setText("Nuevo Cliente");

        botonEliminarCliente.setText("Eliminar Cliente");

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addComponent(botonNuevoCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonEliminarCliente)
                .addGap(0, 486, Short.MAX_VALUE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(botonNuevoCliente)
                .addComponent(botonEliminarCliente))
        );

        add(panelBotones, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEliminarCliente;
    private javax.swing.JButton botonNuevoCliente;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JScrollPane jsp;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JTable tablaClientes;
    // End of variables declaration//GEN-END:variables
}
