package catalogo.vistas;

import catalogo.controladores.JPA.OrdenDeCompraJpaController;
import catalogo.modelo.Producto;
import catalogo.vistas.modelo.CatalogoListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Mauro Federico Lopez
 */
public class CatalogoUI extends javax.swing.JPanel {

    private CatalogoListModel catalogoListModel;
    private OrdenDeCompraJpaController ordenDeCompraJpaController;
    private Producto producto = null;

    /**
     * Creates new form CatalogoUI
     */
    public CatalogoUI() {
        initComponents();
    }

    public CatalogoUI(OrdenDeCompraJpaController ordenDeCompraJpaController) {
        this();
        this.ordenDeCompraJpaController = ordenDeCompraJpaController;
        catalogoListModel = new CatalogoListModel();
        lista.setModel(catalogoListModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        etiquetaImagen = new javax.swing.JLabel();
        panelInformacion = new javax.swing.JPanel();
        etiquetaCodigo = new javax.swing.JLabel();
        jspAreaTexto = new javax.swing.JScrollPane();
        campoDescripcion = new javax.swing.JTextArea();
        etiquetaPrecio = new javax.swing.JLabel();
        etiquetaCantidad = new javax.swing.JLabel();
        campoCantidad = new javax.swing.JSpinner();
        botonAgregarProducto = new javax.swing.JButton();
        campoPrecio = new javax.swing.JFormattedTextField();
        campoCodigo = new javax.swing.JTextField();
        jspLista = new javax.swing.JScrollPane();
        lista = new javax.swing.JList();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Catálogo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20))); // NOI18N
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setLayout(new java.awt.BorderLayout());

        panel.setLayout(new java.awt.BorderLayout());
        panel.add(etiquetaImagen, java.awt.BorderLayout.CENTER);

        panelInformacion.setMaximumSize(new java.awt.Dimension(488, 100));
        panelInformacion.setMinimumSize(new java.awt.Dimension(488, 100));

        etiquetaCodigo.setText("Código");

        campoDescripcion.setColumns(20);
        campoDescripcion.setEditable(false);
        campoDescripcion.setRows(5);
        jspAreaTexto.setViewportView(campoDescripcion);

        etiquetaPrecio.setText("Precio unitario");

        etiquetaCantidad.setText("CANTIDAD");

        campoCantidad.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(1L), Long.valueOf(1L), null, Long.valueOf(1L)));

        botonAgregarProducto.setText("Agregar Producto al Carrito");
        botonAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarProductoActionPerformed(evt);
            }
        });

        campoPrecio.setEditable(false);
        campoPrecio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        campoCodigo.setEditable(false);

        javax.swing.GroupLayout panelInformacionLayout = new javax.swing.GroupLayout(panelInformacion);
        panelInformacion.setLayout(panelInformacionLayout);
        panelInformacionLayout.setHorizontalGroup(
            panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jspAreaTexto)
                    .addGroup(panelInformacionLayout.createSequentialGroup()
                        .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInformacionLayout.createSequentialGroup()
                                .addComponent(etiquetaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(etiquetaPrecio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelInformacionLayout.createSequentialGroup()
                                .addComponent(etiquetaCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 158, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelInformacionLayout.setVerticalGroup(
            panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaCodigo)
                    .addComponent(etiquetaPrecio)
                    .addComponent(campoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspAreaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaCantidad)
                    .addComponent(campoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAgregarProducto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel.add(panelInformacion, java.awt.BorderLayout.PAGE_END);

        add(panel, java.awt.BorderLayout.CENTER);

        jspLista.setMaximumSize(new java.awt.Dimension(150, 32767));
        jspLista.setMinimumSize(new java.awt.Dimension(150, 23));
        jspLista.setPreferredSize(new java.awt.Dimension(150, 130));

        lista.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaMouseClicked(evt);
            }
        });
        jspLista.setViewportView(lista);

        add(jspLista, java.awt.BorderLayout.LINE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void listaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaMouseClicked
        Integer indiceSeleccionado = lista.getSelectedIndex();
        if(indiceSeleccionado >= 0) {
            producto = (Producto) catalogoListModel.getElementAt(indiceSeleccionado);
            etiquetaImagen.setIcon(new ImageIcon(producto.getImagen()));
            campoCodigo.setText(producto.getCodigo());
            campoPrecio.setValue(producto.getPrecio());
            campoDescripcion.setText("Descripción: " + producto.getDescripcion());
        }
        lista.clearSelection();
    }//GEN-LAST:event_listaMouseClicked

    private void botonAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarProductoActionPerformed
        try {
            if (producto != null) {
                Long cantidad = ((Number) campoCantidad.getValue()).longValue();
                ordenDeCompraJpaController.agregarProducto(producto, cantidad);
            } else {
                throw new Exception("No ha seleccionado ningún producto del catálogo.");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonAgregarProductoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarProducto;
    private javax.swing.JSpinner campoCantidad;
    private javax.swing.JTextField campoCodigo;
    private javax.swing.JTextArea campoDescripcion;
    private javax.swing.JFormattedTextField campoPrecio;
    private javax.swing.JLabel etiquetaCantidad;
    private javax.swing.JLabel etiquetaCodigo;
    private javax.swing.JLabel etiquetaImagen;
    private javax.swing.JLabel etiquetaPrecio;
    private javax.swing.JScrollPane jspAreaTexto;
    private javax.swing.JScrollPane jspLista;
    private javax.swing.JList lista;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelInformacion;
    // End of variables declaration//GEN-END:variables
}
