package catalogo.vistas;

/**
 *
 * @author Mauro Federico Lopez
 */
public class ClienteUI extends javax.swing.JFrame {

    /**
     * Creates new form ClienteUI
     */
    public ClienteUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        jmArchivo = new javax.swing.JMenu();
        jmiVolver = new javax.swing.JMenuItem();
        jmiSalir = new javax.swing.JMenuItem();
        jmVer = new javax.swing.JMenu();
        jmiCatalogo = new javax.swing.JMenuItem();
        jmiOrdenesPendientes = new javax.swing.JMenuItem();
        jmiMisDatos = new javax.swing.JMenuItem();
        jmAyuda = new javax.swing.JMenu();
        jmiAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmArchivo.setMnemonic('f');
        jmArchivo.setText("Archivo");

        jmiVolver.setText("Volver");
        jmArchivo.add(jmiVolver);

        jmiSalir.setMnemonic('x');
        jmiSalir.setText("Salir");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        jmArchivo.add(jmiSalir);

        menuBar.add(jmArchivo);

        jmVer.setMnemonic('e');
        jmVer.setText("Ver");

        jmiCatalogo.setMnemonic('t');
        jmiCatalogo.setText("Catálogo");
        jmVer.add(jmiCatalogo);

        jmiOrdenesPendientes.setMnemonic('y');
        jmiOrdenesPendientes.setText("Órdenes de Compra Pendientes");
        jmVer.add(jmiOrdenesPendientes);

        jmiMisDatos.setMnemonic('d');
        jmiMisDatos.setText("Mis Datos");
        jmVer.add(jmiMisDatos);

        menuBar.add(jmVer);

        jmAyuda.setMnemonic('h');
        jmAyuda.setText("Ayuda");

        jmiAcercaDe.setMnemonic('a');
        jmiAcercaDe.setText("Acerca De");
        jmAyuda.add(jmiAcercaDe);

        menuBar.add(jmAyuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 664, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmiSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ClienteUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jmArchivo;
    private javax.swing.JMenu jmAyuda;
    private javax.swing.JMenu jmVer;
    private javax.swing.JMenuItem jmiAcercaDe;
    private javax.swing.JMenuItem jmiCatalogo;
    private javax.swing.JMenuItem jmiMisDatos;
    private javax.swing.JMenuItem jmiOrdenesPendientes;
    private javax.swing.JMenuItem jmiSalir;
    private javax.swing.JMenuItem jmiVolver;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
}
