package catalogo.vistas;

import catalogo.controladores.JPA.OrdenDeCompraJpaController;
import catalogo.modelo.OrdenCompra;
import catalogo.modelo.ProductoOrdenCompra;
import catalogo.vistas.modelo.OrdenesDeCompraTableModel;
import catalogo.vistas.modelo.ProductoOrdenDeCompraTableModel;
import java.util.ArrayList;

/**
 *
 * @author Mauro Federico Lopez
 */
public class HistorialOrdenesDeCompraUI extends javax.swing.JPanel {

    private OrdenesDeCompraTableModel ordenesDeCompraTableModel;
    private ProductoOrdenDeCompraTableModel productoOrdenDeCompraTableModel;

    /**
     * Creates new form HistorialOrdenesDeCompraUI
     */
    public HistorialOrdenesDeCompraUI() {
        initComponents();
    }

    public HistorialOrdenesDeCompraUI(OrdenDeCompraJpaController ordenDeCompraJpaController) {
        this();
        ordenesDeCompraTableModel = new OrdenesDeCompraTableModel(ordenDeCompraJpaController);
        productoOrdenDeCompraTableModel = new ProductoOrdenDeCompraTableModel();
        tablaOrdenesDeCompra.setModel(ordenesDeCompraTableModel);
        tablaProductosOrdenDeCompra.setModel(productoOrdenDeCompraTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspTablaOrdenCompra = new javax.swing.JScrollPane();
        tablaOrdenesDeCompra = new javax.swing.JTable();
        jspTablaProductoOrdenCompra = new javax.swing.JScrollPane();
        tablaProductosOrdenDeCompra = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Historial de órdenes de compra", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20))); // NOI18N
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setLayout(new java.awt.BorderLayout());

        tablaOrdenesDeCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaOrdenesDeCompra.getTableHeader().setReorderingAllowed(false);
        tablaOrdenesDeCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaOrdenesDeCompraMouseClicked(evt);
            }
        });
        jspTablaOrdenCompra.setViewportView(tablaOrdenesDeCompra);

        add(jspTablaOrdenCompra, java.awt.BorderLayout.CENTER);

        jspTablaProductoOrdenCompra.setMaximumSize(new java.awt.Dimension(32767, 200));
        jspTablaProductoOrdenCompra.setMinimumSize(new java.awt.Dimension(23, 200));
        jspTablaProductoOrdenCompra.setPreferredSize(new java.awt.Dimension(452, 200));

        tablaProductosOrdenDeCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaProductosOrdenDeCompra.getTableHeader().setReorderingAllowed(false);
        jspTablaProductoOrdenCompra.setViewportView(tablaProductosOrdenDeCompra);

        add(jspTablaProductoOrdenCompra, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void tablaOrdenesDeCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaOrdenesDeCompraMouseClicked
        int filaSeleccionada = tablaOrdenesDeCompra.getSelectedRow();
        if(filaSeleccionada >= 0) {
            OrdenCompra ordenDeCompra = ordenesDeCompraTableModel.obtenerOrdenDeCompra(filaSeleccionada);
            ArrayList<ProductoOrdenCompra> productosDeOrdenCompra = ordenDeCompra.getProductosDeOrdenCompra();
            productoOrdenDeCompraTableModel.setProductosOrdenDeCompra(productosDeOrdenCompra);
        }
        tablaOrdenesDeCompra.clearSelection();
    }//GEN-LAST:event_tablaOrdenesDeCompraMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jspTablaOrdenCompra;
    private javax.swing.JScrollPane jspTablaProductoOrdenCompra;
    private javax.swing.JTable tablaOrdenesDeCompra;
    private javax.swing.JTable tablaProductosOrdenDeCompra;
    // End of variables declaration//GEN-END:variables
}
