package catalogo.vistas;

import catalogo.vistas.modelo.ClienteTableListener;
import catalogo.vistas.modelo.ClienteTableModel;

/**
 *
 * @author Mauro Federico Lopez
 */
public class MisClientes extends javax.swing.JInternalFrame {

    private ClienteTableModel modeloTabla;
    private ClienteTableListener modeloOyente;

    /**
     * Creates new form MisClientes
     */
    public MisClientes() {
        initComponents();
        modeloTabla = new ClienteTableModel();
        modeloOyente = new ClienteTableListener(this);
        jtMisClientes.getSelectionModel().addListSelectionListener(modeloOyente);
        jtMisClientes.setModel(modeloTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jsp = new javax.swing.JScrollPane();
        jtMisClientes = new javax.swing.JTable();
        JlTitulo = new javax.swing.JLabel();
        jbEliminar = new javax.swing.JButton();

        setBorder(null);
        setForeground(java.awt.Color.white);
        setTitle("Mis Clientes");

        jtMisClientes.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jtMisClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "N°Cliente", "Apellido y Nombre", "Correo", "Télefono"
            }
        ));
        jsp.setViewportView(jtMisClientes);

        JlTitulo.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        JlTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlTitulo.setText("Mis Clientes");

        jbEliminar.setText("Eliminar Cliente");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jsp, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jbEliminar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsp, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbEliminar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        getModeloTabla().eliminarCliente(getJtMisClientes().getSelectedRow());
    }//GEN-LAST:event_jbEliminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlTitulo;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JScrollPane jsp;
    private javax.swing.JTable jtMisClientes;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the modeloTabla
     */
    public ClienteTableModel getModeloTabla() {
        return modeloTabla;
    }

    /**
     * @param modeloTabla the modeloTabla to set
     */
    public void setModeloTabla(ClienteTableModel modeloTabla) {
        this.modeloTabla = modeloTabla;
    }

    /**
     * @return the JlTitulo
     */
    public javax.swing.JLabel getJlTitulo() {
        return JlTitulo;
    }

    /**
     * @param JlTitulo the JlTitulo to set
     */
    public void setJlTitulo(javax.swing.JLabel JlTitulo) {
        this.JlTitulo = JlTitulo;
    }

    /**
     * @return the jbEliminar
     */
    public javax.swing.JButton getJbEliminar() {
        return jbEliminar;
    }

    /**
     * @param jbEliminar the jbEliminar to set
     */
    public void setJbEliminar(javax.swing.JButton jbEliminar) {
        this.jbEliminar = jbEliminar;
    }

    /**
     * @return the jsp
     */
    public javax.swing.JScrollPane getJsp() {
        return jsp;
    }

    /**
     * @param jsp the jsp to set
     */
    public void setJsp(javax.swing.JScrollPane jsp) {
        this.jsp = jsp;
    }

    /**
     * @return the jtMisClientes
     */
    public javax.swing.JTable getJtMisClientes() {
        return jtMisClientes;
    }

    /**
     * @param jtMisClientes the jtMisClientes to set
     */
    public void setJtMisClientes(javax.swing.JTable jtMisClientes) {
        this.jtMisClientes = jtMisClientes;
    }
}
