package catalogo.vistas;

import java.awt.BorderLayout;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;

/**
 *
 * @author Mauro Federico Lopez
 */
public class ProveedorUI extends javax.swing.JFrame {

    /**
     * Creates new form ProveedorUI
     */
    public ProveedorUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        jmiArchivo = new javax.swing.JMenu();
        jmiVolver = new javax.swing.JMenuItem();
        jmiSalir = new javax.swing.JMenuItem();
        jmiAdministrar = new javax.swing.JMenu();
        jmiProductos = new javax.swing.JMenuItem();
        jmiClientes = new javax.swing.JMenuItem();
        jmiOrdenesCompra = new javax.swing.JMenuItem();
        jmAyuda = new javax.swing.JMenu();
        jmiAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmiArchivo.setMnemonic('f');
        jmiArchivo.setText("Archivo");

        jmiVolver.setMnemonic('a');
        jmiVolver.setText("Volver");
        jmiArchivo.add(jmiVolver);

        jmiSalir.setMnemonic('x');
        jmiSalir.setText("Salir");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        jmiArchivo.add(jmiSalir);

        menuBar.add(jmiArchivo);

        jmiAdministrar.setMnemonic('e');
        jmiAdministrar.setText("Administrar");

        jmiProductos.setMnemonic('t');
        jmiProductos.setText("Productos");
        jmiProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProductosActionPerformed(evt);
            }
        });
        jmiAdministrar.add(jmiProductos);

        jmiClientes.setMnemonic('y');
        jmiClientes.setText("Clientes");
        jmiClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiClientesActionPerformed(evt);
            }
        });
        jmiAdministrar.add(jmiClientes);

        jmiOrdenesCompra.setMnemonic('p');
        jmiOrdenesCompra.setText("Órdenes de Compra");
        jmiAdministrar.add(jmiOrdenesCompra);

        menuBar.add(jmiAdministrar);

        jmAyuda.setMnemonic('h');
        jmAyuda.setText("Ayuda");

        jmiAcercaDe.setMnemonic('a');
        jmiAcercaDe.setText("Acerca De");
        jmiAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAcercaDeActionPerformed(evt);
            }
        });
        jmAyuda.add(jmiAcercaDe);

        menuBar.add(jmAyuda);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
        
    }//GEN-LAST:event_jmiSalirActionPerformed

    private void jmiClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiClientesActionPerformed
        agregarComponenteAlCentro(new AdministrarClientesUI());
    }//GEN-LAST:event_jmiClientesActionPerformed

    private void jmiAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAcercaDeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiAcercaDeActionPerformed

    private void jmiProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProductosActionPerformed
        agregarComponenteAlCentro(new AdministrarProductosUI());
    }//GEN-LAST:event_jmiProductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProveedorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProveedorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProveedorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProveedorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new ProveedorUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jmAyuda;
    private javax.swing.JMenuItem jmiAcercaDe;
    private javax.swing.JMenu jmiAdministrar;
    private javax.swing.JMenu jmiArchivo;
    private javax.swing.JMenuItem jmiClientes;
    private javax.swing.JMenuItem jmiOrdenesCompra;
    private javax.swing.JMenuItem jmiProductos;
    private javax.swing.JMenuItem jmiSalir;
    private javax.swing.JMenuItem jmiVolver;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

    private void agregarComponenteAlCentro(JComponent componente) {
        getContentPane().removeAll();
        add(componente, BorderLayout.CENTER);
        componente.setVisible(true);
        componente.updateUI();
        pack();
    }
}
