package catalogo.vistas;

import java.awt.BorderLayout;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;

/**
 *
 * @author Mauro Federico Lopez
 */
public class ProveedorUI extends javax.swing.JFrame {

    /**
     * Creates new form ProveedorUI
     */
    public ProveedorUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        jmiAdministrar = new javax.swing.JMenu();
        jmiProductos = new javax.swing.JMenuItem();
        jmiClientes = new javax.swing.JMenuItem();
        jmiOrdenesCompra = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proveedor");
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));

        jmiAdministrar.setMnemonic('e');
        jmiAdministrar.setText("Administrar");

        jmiProductos.setMnemonic('t');
        jmiProductos.setText("Productos");
        jmiProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProductosActionPerformed(evt);
            }
        });
        jmiAdministrar.add(jmiProductos);

        jmiClientes.setMnemonic('y');
        jmiClientes.setText("Clientes");
        jmiClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiClientesActionPerformed(evt);
            }
        });
        jmiAdministrar.add(jmiClientes);

        jmiOrdenesCompra.setMnemonic('p');
        jmiOrdenesCompra.setText("Órdenes de Compra");
        jmiOrdenesCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiOrdenesCompraActionPerformed(evt);
            }
        });
        jmiAdministrar.add(jmiOrdenesCompra);

        menuBar.add(jmiAdministrar);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiClientesActionPerformed
        agregarComponenteAlCentro(new AdministrarVendedoresUI());
    }//GEN-LAST:event_jmiClientesActionPerformed

    private void jmiProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProductosActionPerformed
        agregarComponenteAlCentro(new AdministrarProductosUI());
    }//GEN-LAST:event_jmiProductosActionPerformed

    private void jmiOrdenesCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiOrdenesCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiOrdenesCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProveedorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProveedorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProveedorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProveedorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new ProveedorUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jmiAdministrar;
    private javax.swing.JMenuItem jmiClientes;
    private javax.swing.JMenuItem jmiOrdenesCompra;
    private javax.swing.JMenuItem jmiProductos;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

    private void agregarComponenteAlCentro(JComponent componente) {
        getContentPane().removeAll();
        add(componente, BorderLayout.CENTER);
        componente.setVisible(true);
        componente.updateUI();
        pack();
    }
}
