package catalogo.vistas;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;

/**
 *
 * @author Mauro Federico Lopez
 */
public class Proveedor extends javax.swing.JFrame {

    private MisClientes misClientes;
    /**
     * Creates new form Proveedor
     */
    public Proveedor() {
        initComponents();
        misClientes = new MisClientes();
        misClientes.setVisible(false);
        desktopPane.add(misClientes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        jmiArchivo = new javax.swing.JMenu();
        jmiVolver = new javax.swing.JMenuItem();
        jmiSalir = new javax.swing.JMenuItem();
        jmiVer = new javax.swing.JMenu();
        jmiMisProductos = new javax.swing.JMenuItem();
        jmiMisClientes = new javax.swing.JMenuItem();
        jmiOrdenesCompra = new javax.swing.JMenuItem();
        jmAyuda = new javax.swing.JMenu();
        jmiAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmiArchivo.setMnemonic('f');
        jmiArchivo.setText("Archivo");

        jmiVolver.setMnemonic('a');
        jmiVolver.setText("Volver");
        jmiArchivo.add(jmiVolver);

        jmiSalir.setMnemonic('x');
        jmiSalir.setText("Salir");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        jmiArchivo.add(jmiSalir);

        menuBar.add(jmiArchivo);

        jmiVer.setMnemonic('e');
        jmiVer.setText("Ver");

        jmiMisProductos.setMnemonic('t');
        jmiMisProductos.setText("Mis Productos");
        jmiVer.add(jmiMisProductos);

        jmiMisClientes.setMnemonic('y');
        jmiMisClientes.setText("Mis Clientes");
        jmiMisClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMisClientesActionPerformed(evt);
            }
        });
        jmiVer.add(jmiMisClientes);

        jmiOrdenesCompra.setMnemonic('p');
        jmiOrdenesCompra.setText("Órdenes de Compra");
        jmiVer.add(jmiOrdenesCompra);

        menuBar.add(jmiVer);

        jmAyuda.setMnemonic('h');
        jmAyuda.setText("Ayuda");

        jmiAcercaDe.setMnemonic('a');
        jmiAcercaDe.setText("Acerca De");
        jmAyuda.add(jmiAcercaDe);

        menuBar.add(jmAyuda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmiSalirActionPerformed

    private void jmiMisClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMisClientesActionPerformed
        try {
            misClientes.setVisible(true);
            misClientes.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Proveedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jmiMisClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Proveedor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jmAyuda;
    private javax.swing.JMenuItem jmiAcercaDe;
    private javax.swing.JMenu jmiArchivo;
    private javax.swing.JMenuItem jmiMisClientes;
    private javax.swing.JMenuItem jmiMisProductos;
    private javax.swing.JMenuItem jmiOrdenesCompra;
    private javax.swing.JMenuItem jmiSalir;
    private javax.swing.JMenu jmiVer;
    private javax.swing.JMenuItem jmiVolver;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
}
